//USERS
export const USER_REGISTRATION = "USER_REGISTRATION";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR ";
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const GETTING_MY_PROFILE_ERROR = "GETTING_MY_PROFILE_ERROR";
//POST
//==============
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const POST_CREATED = "POST_CREATED";
export const POST_CREATED_ERROR = "POST_CREATED_ERROR";
