//USERS
export const USER_REGISTRATION = "USER_REGISTRATION";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR ";
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
